services:
  db:
    image: "postgres:15"
    container_name: email-api-db
    environment:
      POSTGRES_DB: email_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: email
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5435:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-api-app
    volumes:
      - ".:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - db
  webserver:
    image: nginx:latest
    container_name: email-api-webserver
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - app
  queue:
    image: "redis:alpine"
    container_name: email-api-queue
    ports:
      - "6375:6379"
    volumes:
      - "redisdata:/data"

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
