CREATE TABLE IF NOT EXISTS sent_emails (
    id SERIAL PRIMARY KEY,
    "to" VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
